"""posts table

Revision ID: 6b2811840208
Revises: 5c0bd85e074b
Create Date: 2023-09-16 00:14:32.451479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2811840208'
down_revision = '5c0bd85e074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temp2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_post_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('comment')
        batch_op.drop_column('time2')
        batch_op.drop_column('time1')
        batch_op.drop_column('temp2')
        batch_op.drop_column('temp1')

    # ### end Alembic commands ###
